### ISSUE TITLE
tutorial : when the master drops out after having picked up a vital

### ISSUE THREAD

**Issue by laurentopia** [emotitron/Simple_Addon_for_Pun2#1]
the vital sticks to the ground and cannot be picked up by the other players
if a new player enters the room after that, the vital will not be in the same place
ie: the world isn't synchronized to new players when the master drops out or maybe it's a function of the vital

a player that saw the master drop out
![image](https://user-images.githubusercontent.com/26075468/80122769-d4a2db80-8542-11ea-90cc-ddd553bf1b33.png)

new player
![image](https://user-images.githubusercontent.com/26075468/80122754-d076be00-8542-11ea-8cb3-5afe4e711b3c.png)

**Comment by laurentopia** [comment]
that vital that got dropped by the master, unresponsive:
![image](https://user-images.githubusercontent.com/26075468/80122946-16338680-8543-11ea-95e2-496d8001a7b3.png)

**Comment by emotitron** [comment]
Edge case surrounding change of authority are definitely still needing to
be tested and accounted for.

I'll see if I can come up with some clean answers for that case though.
Master leaving a game is notoriously tricky to handle on PUN.

Thanks for the catch!

**Comment by laurentopia** [comment]
I thought auto host migration also handled master reassignment. Can you explain?

**Comment by emotitron** [comment]
The master changes to the next connection. However dropping a client
requires immediate action when it comes to nested networked objects (so
that children don't get destroyed with it). This forces reparenting and
State changes outside of SNSs very strict deferred tick/update mechanisms,
so it creates an edge case that will require ongoing work to catch all edge
cases and avoid race conditions.

**Comment by emotitron** [comment]
Looking into this issue, it is one of the primary issues I am working on
with the PUN team. I basically need a callback from PUN BEFORE any
networked objects get destroyed due to disconnect or timeout. Right now I
have to detect the destruction with the OnDestroy and OnDisable methods,
which is already too late to prevent Unity from disabling all components.

**Comment by laurentopia** [comment]
We didn't use the autocleanup to allow for friendly recovery in case of short disconnect.
Everything was done by hand. 
I never dared looking at our net code until now but at a glance it's not that bad, just a lot of edge cases such as in-transit turret, ongoing upgrades. Have a look and tell me what you think of it and how SNS would help.
https://pastebin.com/QeadUwXy

**Comment by emotitron** [comment]
@laurentopia I have finally gotten a chance to add the needed callbacks to PUN2 that notify all gameobjects that they are about to be destroyed for networking reasons.

It will be a bit before it gets into the store release of PUN2, but when it does I will update SNS with the update.

The basic is/was that PUN actively discourages and doesn't support nested PVs, I am right now working on the library to make it support nesting (or at the very least not fight my attempts with SNS to do it). The lack of callbacks surrounding network object destruction was the main hurdle to it fully working.

**Comment by laurentopia** [comment]
That's great.
That'll make equip/unequip much easier.

**Comment by emotitron** [comment]
The change needed had been added to Pun2. Can't push a new SNS that makes
use of it until the next pun release.

**Comment by laurentopia** [comment]
Keep me posted, I'm very interested.

**Comment by emotitron** [comment]
The new Pun2 version 2.19 on the store has built in support for detaching
unowned nested objects when a player leaves. I'll be releasing a new SNS
shortly now that that is out - but the Pun2 part might on its own fix the
issue with nested objects and destruction.

Cheers!
