### ISSUE TITLE
Are Vitals, HitBox etc... gameplay samples?

### ISSUE THREAD

**Issue by laurentopia** [emotitron/Simple_Addon_for_Pun2#2]
Or core to SNS?
I see a wide support for interface in these which indicates that this lib is a sort of game builder.
I guess before I invest more time in it I'd like to know your direction.

**Comment by emotitron** [comment]
I can't really get too deep into explaining the library through email, but
if you join the Photon Engine discord I am happy to discuss current plans
and the current direction when I am free. That way others can read the
discussion as well.

https://discord.gg/Djuswk

Cheers!
D
