### ISSUE TITLE
SyncVar is not working 

### ISSUE THREAD

**Issue by myrisee** [emotitron/Simple_Addon_for_Pun2#3]
SyncVar attribute is not working in my project.

I wrote some scripts and tried to sync some values but it didnt work.

I double checked everything. Class have PackObject attribute at top and gameobject have NetObject & PhotonView also.

Tried to run TestPackObject.cs but original test is not working too but SyncTransform is working okey.

Any idea ?

Unity 2020.2.7f1 - PUN 2  v2.29

**Comment by emotitron** [comment]
Be sure code gen is enabled in the pack object settings. In recent versions
it's been disabled by default. If that doesn't work,, you may want to ping
me on discord.

**Comment by myrisee** [comment]
I couldnt find the Discord link

**Comment by emotitron** [comment]
https://discord.gg/egaRfd8

That should get you the Pun2 public discord - just ping me in there - I am
emotitron.

**Comment by myrisee** [comment]
Issue is solved with help of @emotitron thanks

**Comment by TheXRMonk** [comment]
Can you please explain the solution? I have similar issues with just syncing a simple float. PackObjectsSettings finds the field correctly, but it's not updated on the client. Built-in views (transform for instance) work.

**Comment by emotitron** [comment]
> Can you please explain the solution? I have similar issues with just syncing a simple float. PackObjectsSettings finds the field correctly, but it's not updated on the client. Built-in views (transform for instance) work.

You have AutoGenerate enabled (in PackObjectSettings)? And are there any errors in the log?

If you are just getting started on a project, I would recommend looking into the Fusion beta, as all work is focused there at the moment, and that library is designed do everything Pun+ Simple can do - and will have a great deal more support and features going forward.

**Comment by TheXRMonk** [comment]
> > Can you please explain the solution? I have similar issues with just syncing a simple float. PackObjectsSettings finds the field correctly, but it's not updated on the client. Built-in views (transform for instance) work.
> 
> You have AutoGenerate enabled (in PackObjectSettings)? And are there any errors in the log?

Yes, AutoGenerate is enabled.
I'm only getting this every other second or so.
`Critically Late Update conn: 1  Incoming Frame: 2 Current Interpolation: 16->17 DATA LOSS HAS OCCURRED EVEN FOR RELIABLE PACKETS. Increase Buffer size in TickEngineSettings.`
Even though the buffer size is 1.6 ms and tickrate is 6/sec (0.16ms).

> If you are just getting started on a project, I would recommend looking into the Fusion beta, as all work is focused there at the moment, and that library is designed do everything Pun+ Simple can do - and will have a great deal more support and features going forward.

Thanks for this info! Oddly I never came across this product - will give it a look.

**Comment by TheXRMonk** [comment]
Alrighty, have been investing the day into testing the fusion API, and while it looks very nifty it lacks the option of easily networking a big(~200) array of vector3's. The [Networked] attribute only takes primitives, where they SyncVar could take lists and arrays. 

The vectors I'm trying to sync are particle positions of a physics simulated rope, but it also looks like Fusion may be able to just sync the users applied changes and make the rope appear deterministic across all clients. Or do I still need to sync the whole rope to make sure it's in sync? 

Apologies in advance if I'm asking in the wrong place. Please redirect me if necessary :)

**Comment by emotitron** [comment]
@myrisee 
Be sure to hop on the PhotonEngine discord, there is a Fusion channel where you can get help as you go:
https://discord.gg/PyGKYGyUM6

Fusion has a NetworkArray<T> type for arrays.
